import { MateriaConfig } from '@/types';

export const founderSoloMasterclass: MateriaConfig = {
  slug: 'founder-solo-masterclass',
  nome: 'Founder Solo: O Jogo Infinito',
  emoji: '🦅',
  isCategory: false,
  descricao: 'The complete learning sequence for the solo founder — crossing engineering, sales, psychology, finance, AI, neuroscience of perception, quantum physics, behavioral economics, geopolitics, rhetoric, power dynamics, mimetic theory, and philosophy into a single progressive curriculum with no artificial silos.',
  contexto: `PERSONA:\nYou are a seasoned solo founder who has built, scaled, and exited multiple software businesses without ever hiring an employee. You are pragmatic, ruthless with your time, and leverage technology to punch 100x above your weight class. Never break this frame. You are not a generic AI — you are this specialist.\n\nYou are teaching Tiago, a solo founder at Ybernator. He is simultaneously the developer, marketer, salesperson, support agent, and CFO.

CORE TEACHING MANDATE:
- The student must understand the MECHANISM behind every concept, not just the tactic.
- Cross-reference disciplines aggressively: when teaching pricing, connect it to mimetic theory, prospect theory, AND neuroscience of pain.
- For every concept: explain WHY it matters for a solo founder with zero team and limited runway.
- Treat the student as a capable adult who can handle hard truths about risk, failure, and trade-offs.
- If a topic has a famous source (book, person, study), cite it explicitly. If not, say so.
- When physics, neuroscience, or history appears — explain the MECHANISM first, then its indirect leverage for the founder.

ANTI-PATTERNS TO AVOID:
- Never reduce complexity to motivational slogans.
- Never give a checklist without explaining the mechanism behind each item.
- Never assume the student has a team, a budget, or a safety net.`,
  ementa: [
    // ─── Ciclo 1 ───────────────────────────────────────────────────────────────
    'O Jogo do Founder Solo: Por que 1 Pessoa com Alavancagem Bate Times de 10 Sem Ela',
    'O Cérebro como Máquina de Inferência Bayesiana: Como o Usuário Não Vê o Seu Produto — Ele Infere',
    'Entropia e a Seta do Tempo: Por Que Sistemas (Empresas, Produtos, Times) Decaem Sem Energia Constante',
    'Sistema 1 e Sistema 2 de Kahneman: Como a Decisão do Seu Cliente Acontece Antes da Razão',
    'O Ciclo da Adenosina: O Mecanismo Bioquímico do Cansaço — e o Protocolo de Atraso da Cafeína (90-120 min)',
    'Teoria Mimética de René Girard: O Desejo é Sempre Mediado por um Outro — O que Isso Diz sobre Viral Loops',
    'O Triângulo de Aristóteles: Ethos, Pathos e Logos — A Estrutura de Todo Pitch, Cold Email e Landing Page',
    'Capital Social, Cultural, Simbólico e Econômico: A Teoria dos 4 Capitais de Bourdieu — e Qual o Founder Solo Mais Precisa',
    'O Marcador Somático de Damasio: Emoção como Sinal de Valor — Por Que UX Fria Não Converte',
    'A Primeira Venda: Como Fazer Alguém Pagar Antes do Produto Estar Pronto — Pré-Venda como Validação',
    'Value-Based Pricing: Cobrar pelo Valor Gerado pelo Cliente, Não pelo Custo de Produção',
    'Desglobalização (Peter Zeihan): O Fim do Sistema que os EUA Garantiram — e o Que Isso Muda Para SaaS Global',
    'Falsificacionismo (Popper): O Que Faz Uma Hipótese de Produto Ser Científica — e Como Testar Sem Viés',
    'Síndrome do Impostor: Mecanismo Neural e Como Operar Mesmo Assim — Não Superar, Gerenciar',
    'O Stack de IA do Founder Solo em 2026: GPT, Claude, Gemini, Perplexity — Mapa de Uso por Tarefa',
    'Arquitetura Monolítica: Por Que Microserviços Matam Solo Founders — Pragmatismo > Elegância',
    'Product-Led Growth (PLG): Projetar o Produto Para Que Ele Seja o Próprio Canal de Aquisição',
    'Leis da Gestalt Aplicadas a Interfaces: Proximidade, Semelhança e Fechamento — Percepção antes de Raciocínio',
    'A Engenharia do Consentimento (Edward Bernays): Como Opiniões São Fabricadas — e Como o Founder Entende o Mercado',
    'Skin in the Game: Por Que o Conselheiro sem Risco É Ruído — Como Filtrar Mentores e Parceiros',
    'O Efeito de Espaçamento (Ebbinghaus e a Curva do Esquecimento): Como Estruturar Aprendizado de Alto Impacto',
    'Feedback Radical (Kim Scott — Radical Candor): Caring Personally + Challenging Directly',
    'A Lei de Potência (Power Law): Distribuição de Retornos em VC, Conteúdo e Produto — Onde Concentrar Esforço',

    // ─── Ciclo 2 ───────────────────────────────────────────────────────────────
    'Burn Rate & Runway: A Matemática Fria do Tempo de Vida da Sua Empresa',
    'Predictive Coding (Anil Seth): A Realidade é uma "Alucinação Controlada" — o Que Isso Significa Para UX',
    'Teoria do Caos e o Efeito Borboleta: Engenharia de Condições Iniciais no Negócio — Pequenas Mudanças, Grandes Divergências',
    'Teoria da Perspectiva (Prospect Theory): O Ponto de Referência que Determina se o Preço Parece Caro ou Barato',
    'Arquitetura do Sono: Fase REM vs Deep Sleep (SWS) e a Limpeza Glifática do Cérebro — Por Que o Fundador Que Não Dorme Decide Mal',
    'O Triângulo do Desejo: Sujeito, Mediador e Objeto — Como Criar Inveja Estratégica pelo Seu Produto',
    'BATNA: Sua Alternativa Determina Seu Poder Real na Mesa — Negociação de Contratos Como Solo Founder',
    'Laços Fracos de Granovetter: Por Que Conhecidos Distantes Abrem Mais Portas que Amigos Próximos',
    'Nucleus Accumbens e a Antecipação do Prazer de Compra: Como Criar Expectativa Antes do Onboarding',
    'ICP (Ideal Customer Profile): Focando num Nicho Minúsculo Para Dominar Antes de Escalar',
    'Freemium vs Free Trial vs Reverse Trial: A Lógica Econômica por Trás de Cada Modelo',
    'A Guerra de Chips e Semicondutores: Por Que Taiwan é o Centro do Mundo — e as Implicações para Infraestrutura Cloud',
    'O Mapa Não é o Território (Korzybski): Modelos São Úteis, Não Verdadeiros — Revisão Constante de Premissas',
    'Identidade e o Perigo de Ser o Seu Negócio (Identity Enmeshment): O Que Acontece Quando o Produto Falha',
    'Prompt Engineering de Alta Precisão: Role, Context, Constraints, Examples — Anatomia do Prompt Cirúrgico',
    'Supabase do Zero: Auth, RLS, Edge Functions e Storage — O BaaS que Substitui um Time de Backend',
    'Growth Loops vs Funil Linear: Por Que Loops Escalam e Funis Têm Teto Estrutural',
    'Heurísticas de Nielsen: Os 10 Princípios que Toda Interface Deve Respeitar — e Por Que Funcionam Neurologicamente',
    'O Papel da Repetição e do Efeito Illusory Truth: Por Que Dizer a Mesma Coisa Muitas Vezes Cria Percepção de Verdade',
    'A Mecânica dos Incentivos (Charlie Munger): Entendendo Por Que Pessoas Fazem o Que Fazem — Alinhamento de Clientes e Parceiros',
    'Recuperação Ativa como Ferramenta Neural (Test Effect): Usar Flashcards e Quizzes Não é Treino — É Retenção',
    'Comunicação Assíncrona Total: Abolindo Reuniões Desnecessárias — Escrita Como Default Operacional',
    'Sustainable Growth: Como Estruturar a Empresa Para Jogar o Jogo Infinito a Longo Prazo',

    // ─── Ciclo 3 ───────────────────────────────────────────────────────────────
    'O Paradoxo do MVP: Produto Mínimo vs Produto Viável — e Por que a Maioria Erra os Dois',
    'O Sistema Ativador Reticular Ascendente (SARA): Por Que Atenção É um Recurso Finito e Não Democrático',
    'O Princípio da Incerteza de Heisenberg: Os Limites Rígidos do Conhecimento do Mercado — e Por que Prever é Menos Valioso que Adaptar',
    'Aversão à Perda: A Assimetria Neural Dor da Perda > Prazer do Ganho — e Como Isso Afeta Seu Pricing',
    'Dopamina Baseline: O Erro de Aumentar a Recompensa Antes de Tarefas de Alto Esforço',
    'Escassez Real vs Escassez Artificial: Construindo Urgência sem Destruir Credibilidade — Waitlists e Drops',
    'A Neurociência do Medo de Falar em Público: Cortisol vs Testosterona — Regulação para Demos que Convertem',
    'A Estrutura dos Buracos Estruturais (Ronald Burt): Posicionando-se como Ponte entre Comunidades — Rede de Distribuição',
    'A Dor do Pagamento (Córtex Insular): Reduzindo a Fricção na Conversão — Checkout Psychology',
    'Discovery Call: As Perguntas Certas Antes de Apresentar Qualquer Coisa — Diagnóstico Antes de Remédio',
    'MRR, ARR, Churn Rate e NRR: A Matemática Real do SaaS que Todo Founder Precisa Dominar',
    'O Grande Ciclo de Ray Dalio: A Arquitetura de Ascensão e Declínio — e os Ciclos de Dívida que Afetam VC e Crédito',
    'Bayesianismo Aplicado: Atualizar Crenças sobre o Produto com Nova Evidência — Sem Ancorar no Primeiro Dado',
    'O Ciclo Emocional do Founder: Euforia, Vale da Morte e Recuperação — O que as Pesquisas Realmente Mostram',
    'Chain-of-Thought Prompting: Fazendo a IA Pensar Passo a Passo em Voz Alta — Quando Usar e Por Quê',
    'Dívida Técnica: Quando é Estratégico Adquiri-la e Quando é Mortal — A Matemática do Custo Diferido',
    'North Star Metric: Encontrar a Única Métrica que Resume o Valor Entregue — Sem Métricas de Vaidade',
    'Neuroestética: Por Que Certos Designs São Esteticamente Convincentes — O Que a Neurociência Confirma',
    'A Janela de Overton: Expandindo o Aceitável no Discurso do Seu Mercado — Educação de Cliente vs Mudança de Categoria',
    'Realpolitik Aplicada ao Negócio: Agir pelo Que É, Não pelo Que Deveria Ser — Competidores, Parceiros e Mercado',
    'O Efeito de Intercalação (Interleaving): Por Que Misturar Assuntos Funciona — O Fundamento Neural',
    'Delegação Efetiva via Freelancers: Como Empacotar Tarefas com Spec Docs',
    'O Founder Aumentado em 2026: Quando Delegar Para IA, Para Humanos, Para Ninguém',

    // ─── Ciclo 4 ───────────────────────────────────────────────────────────────
    'The Mom Test (Rob Fitzpatrick): Como Extrair a Verdade dos Usuários Sem Viés',
    'Processamento Top-Down vs Bottom-Up: Como o Usuário Enxerga Antes de Pensar — Design de Interface',
    'Emergência: Como Regras Simples Geram Complexidade Incompreensível — Aplicado a Produto e Cultura',
    'Ancoragem Cognitiva: A Primeira Oferta Sequestra o Cérebro — Use Isso na Página de Preços',
    'O Estado de Flow (Mihaly Csikszentmihalyi): Como Atingir Imersão Profunda Intencionalmente — Blocos de 90 Min',
    'Efeito Veblen: Bens Cujo Consumo Cresce com o Preço — Quando Subir o Preço Aumenta o Desejo',
    'Framing: O Mesmo Produto, Duas Histórias Completamente Diferentes — A Ciência da Narrativa de Vendas',
    'Transferência de Status por Associação: Como o Prestígio de Outros Vira o Seu — PR e Parcerias Estratégicas',
    'Jobs-to-be-Done (JTBD): O Usuário Não Compra o Produto — Ele Contrata uma Solução para um Progresso',
    'SPIN Selling (Neil Rackham): Situação, Problema, Implicação e Necessidade — A Lógica por Trás',
    'Unit Economics: CAC, LTV e Payback Period — O Que Cada Número Esconde e Revela',
    'A Armadilha de Tucídides (Graham Allison): Quando Potências Emergentes Ameaçam Hegemonias — Janelas de Oportunidade para Startups',
    'Ceticismo Pirrônico: Suspender o Julgamento Quando a Evidência é Fraca — Não Lançar Cedo Demais',
    'Perseverança vs Teimosia: Como Saber a Diferença entre Pivotar e Desistir em Tempo Real',
    'MCP (Model Context Protocol): O Padrão Universal de Conectividade da Anthropic — Claude Integrado ao Seu Sistema',
    'APIs RESTful vs GraphQL vs tRPC: Escolhendo a Via de Menor Atrito Para o Solo Founder',
    'SEO Conversacional e AEO (Answer Engine Optimization): Para Perplexity, ChatGPT e Google AI Overviews',
    'Dark Patterns: O Que Nunca Fazer e Como Identificar na Concorrência — Ética e CAC de Longo Prazo',
    'Câmaras de Eco e Filtros Bolha: Por Que Seu ICP Não Vê o Que Você Vê — e Como Alcançar Além da Câmara',
    'Teoria dos Buracos Estruturais: Você É Mais Valioso Quando É Ponte — Posicionamento no Ecossistema',
    'Chunking: Agrupando Informação para Memória de Longo Prazo — Como Estruturar Documentação Técnica',
    'A Lógica da Sobrevivência Antes da Lógica da Otimização: Founder Solo Não Tem Margem para Erro Sistêmico',
    'Engenharia de Atratores de Probabilidade: Inclinando o Caos a Seu Favor — Condições Iniciais e Efeito Borboleta',

    // ─── Ciclo 5 ───────────────────────────────────────────────────────────────
    'Escolha da Stack Tecnológica: Velocidade de Iteração > Escalabilidade Prematura',
    'Modelos Mentais como Algoritmos de Compressão da Realidade: Reframes que Mudam Decisões',
    'Teoria da Informação de Shannon: O Universo como Computação — Reduzindo Ruído nos Sistemas da Empresa',
    'O Efeito de Decoy: O Terceiro Plano que Vende o Segundo — Arquitetura de Pricing Pages que Convertem',
    'Context Switching Residual (Attention Residue): O Custo Real de Checar o WhatsApp "Só 1 Minuto"',
    'Rivalidade Mimética: Como o Desejo Compartilhado Gera Conflito — e Como Comunidades de Produto Funcionam',
    'Silêncio Estratégico: O Poder de Não Responder Imediatamente — Follow-up Timing e Fechamento',
    'Gerenciamento de Impressões (Erving Goffman): A Dramaturgia do Cotidiano — Personal Branding como Sistema',
    'Onboarding: Engenharia do Momento "Aha!" — O Circuito Neural da Recompensa na Ativação',
    'Gestão de Objeções: As 10 Mais Comuns em SaaS e Como Quebrar Cada Uma Sem Soar Manipulador',
    'Cohort Analysis de Receita: Lendo a Saúde Financeira Longitudinal Além do MRR do Mês',
    'CBDCs (Moedas Digitais de Bancos Centrais) e o Futuro de Pagamentos: Stripe e o Que Vem Depois',
    'Viés de Confirmação Epistêmico: Você Só Vê Validação porque Procura por Ela — Anti-padrão do Founder Apaixonado',
    'Estoicismo Aplicado: O Que Está Sob Seu Controle vs O Que Não Está — Dualidade de Controle de Epicteto',
    'RAG (Retrieval-Augmented Generation): Bases de Conhecimento Privadas Sobre Seu Produto e Clientes',
    'Webhooks e Sistemas Assíncronos: A Cola Invisível entre Stripe e Seu App — Sem Bloquear o UI',
    'Cold Email com Personalização por IA: O Que Funciona em 2026 — Taxa de Resposta, Timing e Tom',
    'UX de Alta Conversão: Reduzindo Fricção no Caminho do Usuário ao Pagamento — Fases do Fluxo',
    'A Lei de Brandolini (Princípio da Assimetria da Besteira): Por Que Refutar Críticas Falsas Custa Mais Que Criar',
    'Exploração vs Explotação: Quando Explorar Novas Possibilidades vs Maximizar o Atual — O Dilema do Founder',
    'A Técnica Feynman: Explicar com Palavras Simples Para Descobrir o Que Você Não Sabe',
    'Accountability vs Blame: Responsabilização Sem Cultura de Medo — Especialmente com Contractors',
    'O Colapso da Possibilidade (Física Quântica Aplicada): O Ato da Decisão Irreversível como Ponto de Inflexão Neural',

    // ─── Ciclo 6 ───────────────────────────────────────────────────────────────
    'Primeiros Princípios (First Principles Thinking): Desmontar Até o Fundamento Irredutível — Musk e Aristóteles na Prática',
    'A Ilusão da Identidade e o Ego como Ferramenta Evolutiva: O Que Isso Diz Sobre Seu Brand Voice',
    'O Princípio da Energia Livre (Karl Friston): Minimizar Surpresa como Estratégia Tanto Neural quanto Empresarial',
    'Desconto Hiperbólico: Por Que Usuários Preferem o Agora ao Melhor Depois — Implicações para Freemium',
    'Fadiga de Decisão (Decision Fatigue): O Motivo pelo Qual Zuckerberg Usa a Mesma Roupa — Aplicado ao Founder',
    'O Loop de Comparação em Redes Sociais: Algoritmos que Alimentam Rivalidade Mimética — Aproveitado por PLG',
    'Steel Man vs Hombre de Palha: Como Pensar e Apresentar Objeções Antes do Cliente — Discovery Call',
    'Poder Posicional vs Poder Pessoal: A Diferença entre Cargo e Influência Real — Negociar sem Título',
    'Hook Model (Nir Eyal): Gatilho → Ação → Recompensa Variável → Investimento — A Mecânica do Hábito Digital',
    'Negociação de Contratos: Como Não Dar Desconto Sem Perder o Cliente — Silêncio, Âncora e Concessão',
    'A Estratégia Barbell de Nassim Taleb: Minimização de Ruína com Maximização de Convexidade — Alocação de Tempo e Capital',
    'Moedas Digitais de Reserva e Desdolarização: O Que Impacta Runway, Câmbio e Receita em Dólar',
    'O Efeito Dunning-Kruger no Empreendedorismo: O Mapa do Que Você Não Sabe Que Não Sabe',
    'Antifragilidade (Nassim Taleb) Aplicada ao Founder: Crescer com Estresse em vez de Quebrar por Ele',
    'Automações No-Code com IA (Make, n8n + LLMs): Multiplicando Capacidade de 1 Para 10 Sem Contratar',
    'Estratégias de Cache (Redis): Evitando Faturas Surpresa de Infra — TTL e Invalidação',
    'Building in Public: Quando Transparência Radical Vira Canal de Aquisição — e Quando Não Funciona',
    'Design System Minimalista: Tokens, Componentes e Consistência Visual como Vantagem Competitiva Solo',
    'Neurônios-Espelho e Empatia no Consumo: Storytelling que Ativa a Rede Espelho do Leitor',
    'Assimetria de Informação: Quem Tem Mais Contexto Sistematicamente Vence — Pesquisa de Mercado como Moat',
    'Construindo um Second Brain (Tiago Forte): Método PARA — Projects, Areas, Resources, Archives',
    'OKRs na Prática Para Founder Solo: O Que Dá Certo e o Que Dá Errado — Foco vs Falsa Ambição',
    'A Filosofia do Negócio: Por Que Você Está Construindo Isso e Para Onde Realmente Quer Ir',

    // ─── Ciclo 7 (finais de cada bloco) ───────────────────────────────────────
    'Ilusões de Ótica e Falhas Cognitivas como Provas Algorítmicas: Heurísticas que Seu Produto Pode Explorar Eticamente',
    'Fractais e Auto-Semelhança: Por Que os Mesmos Padrões de Crescimento Aparecem em Startups, Impérios e Células',
    'Falácia do Custo Irrecuperável (Sunk Cost Fallacy): Quando Pivotar vs Quando Persistir — a Decisão que Mata Fundadores',
    'O Princípio de Pareto 80/20 Levado ao Extremo 64/4: Onde Está o Verdadeiro Impacto das Suas Horas',
    'Posicionamento Anti-Mimético: Ser Desejável por Resistir ao Desejo de Massa — Category Design',
    'Pirâmide de Minto (BLUF): Conclusão Primeiro, Sempre — Emails que São Lidos e Respondidos',
    'A Lei do Silêncio (Robert Greene): Quando Falar Menos Vale Mais que Qualquer Argumento — Posicionamento',
    'LTP (Potenciação de Longo Prazo): O Mecanismo Molecular da Memória — Aprendizado do Usuário Dentro do Produto',
    'Follow-up Estruturado: O Timing, Frequência e Tom que Mantém o Lead Quente Sem Incomodar',
    'Cisnes Negros e Caudas Gordas (Fat Tails): Por Que o Pior Cenário Nunca Está no Plano do Fundador',
    'O Nexo Economia-Política: Como Crises Macroeconômicas Produzem Oportunidades de Mercado para Founders',
    'Pensamento de Segundo Nível (Howard Marks): Consequências das Consequências — Antecipando Efeitos Sistêmicos',
    'Comparação e FOMO: O Loop de Rivalidade Mimética em Redes Sociais — e Como Cortar o Sinal',
    'Vibe Coding: Usando Cursor, Claude Code e Windsurf Para Ser 10x Mais Rápido no Código',
    'Feature Flags: Lançamentos Seguros e Rollbacks Imediatos Sem Downtime — Decoupling Deploy de Release',
    'Newsletter como Ativo de Distribuição: Da Zero a 10k Leitores Sem Pagar por Isso',
    'Wireframing Rápido com v0.dev e Figma: Prototipar Antes de Codar — Validação Visual Sem Engenheiro',
    'Música e Resposta Emocional (Dopamina e Chills): O Sistema Olfativo e Auditivo como Canal de Marca Subestimado',
    'Lei de Conway: Sua Arquitetura de Software Espelha Sua Estrutura Organizacional — Solo Founder Implications',
    'Gestão de Conhecimento Pessoal (PKM): Zettelkasten e Obsidian Para Organizar Ideias de Produto e Negócio',
    'Documentação como Capital: Escrevendo One-Pagers Para Decisões — Modelo Amazon Aplicado ao Solo',

    // ─── Ciclo 8 (tópicos finais restantes) ────────────────────────────────────
    'O Paradoxo da Escolha (Barry Schwartz): Menos Opções Vendem Mais — Simplificação de Produto como Estratégia',
    'Timeboxing Diário: Calendário como a Única Lista de Tarefas que Funciona — Cal Newport na Prática',
    'O Efeito de Espaçamento (Spacing Effect): Por Que Maratonar a Feature não Funciona — Onboarding Faseado',
    'Win/Loss Analysis: Por Que Você Perdeu (ou Ganhou) e o Que Esse Dado Diz sobre Posicionamento e ICP',
    'Bootstrapping vs VC: Os Trade-offs Honestos e Irreversíveis de Cada Caminho em 2026',
    'Skin in the Game (Nassim Taleb): Por Que Quem Não Tem Nada a Perder Não Deve Ser Ouvido — Conselhos e Mentores',
    'Mindset de Crescimento (Dweck) com Suporte Neurobiológico: A Crença no Crescimento Ativa o Cérebro',
    'Agentes Autônomos em 2026: O Que É Real vs Hype — e Como Integrar em Workflows Reais',
    'Segurança Defensiva Básica: XSS, CSRF e SQL Injection — O Checklist Mínimo Não Negociável',
    'Virality Loop e Coeficiente K: Como Calcular e Projetar Crescimento Orgânico por Indicação',
    'Microinterações e Animações de Feedback: Quando UX Encanta e Quando Distrai — Dopamina no Produto',
    'Efeito Halo: Como a Primeira Impressão do Produto Contamina Todas as Percepções Seguintes',
    'Lógica de Sobrevivência Antes de Otimização: O Custo Invisível que Otimistas Nunca Incluem no Cálculo',
    'IA como Parceira de Estudo: Usando LLMs Para Aprender Mais Rápido com Feedback em Tempo Real',
    'Excesso de Confiança (Overconfidence Bias): O Viés que Mata Startups em Estimativas de TAM e Timelines',
    'Controle de Frame: Quem Dita a Realidade da Interação — Aplicado a Sales, Pitch e Entrevistas de Usuário',
    'Storytelling Argumentativo: Narrativa como Veículo de Prova — Estrutura de Case Study que Vende',
  ]
};
