import { MateriaConfig } from '@/types';

export const founderSolo: MateriaConfig = {
  slug: 'founder-solo',
  nome: 'Solo Founder Hub',
  emoji: '🦅',
  isCategory: true,
  descricao: 'Comprehensive development for solo founders: from engineering to sales, native AI, and maximum leverage in 2026.',
  children: [
    {
      slug: 'ia-operacional',
      nome: 'Operational AI & Efficiency',
      emoji: '👷',
      parent: 'founder-solo',
      whyStart: 'Before understanding the mathematical weights of a model, learn to use it as a tool. And for a solo founder, AI is not a luxury — it is the entire team.',
      descricao: 'Daily use for massive personal efficiency gains. Workflows, GPT, Claude, MCP, and automations.',
      contexto: `Focus: brutal personal efficiency tactics and day-to-day workflows.
The student is a "Prompt Bricklayer" evolving into an agent conductor, wanting to resolve tasks quickly and pragmatically.`,
      fases: [
        {
          nome: 'Foundations of the Centaur Operator',
          topicos: [
            'The Centaur Operator Mindset: Human + Machine in Synergy',
            'Anatomy of a High-Precision Prompt (Role, Context, Constraints)',
            'System Prompts vs User Prompts: Instruction Architecture',
            'Context Iteration and Refinement (Chaining)',
            'Comparing Models: GPT vs Claude vs Gemini vs Open Models',
            'Token Cost: Optimizing the API Bill Without Losing Quality',
            'Output Evaluation: How to Measure Real AI Quality'
          ]
        },
        {
          nome: 'Cognitive Strategies and Advanced Prompting',
          topicos: [
            'Few-Shot Prompting: Guiding the Model with Surgical Examples',
            'Chain-of-Thought: Making the AI Think Step by Step Out Loud',
            'Tree-of-Thought: Exploring Multiple Reasoning Branches Simultaneously',
            'Meta-Prompting: Using One AI to Generate the Perfect Prompt for Another',
            'Prompt Caching: Optimizing Latency and Cost in Long Contexts',
            'Extended Reasoning (o1, R1 Models): When and How to Use Slow Thinking'
          ]
        },
        {
          nome: 'Productivity, Content, and Daily Operations',
          topicos: [
            'Automating Repetitive Administrative Tasks (Emails, Meetings, Summaries)',
            'Using AI for Research, Book Synthesis, and Market Mapping',
            'AI as a Co-author for Content Creation (Blog, LinkedIn, X, Newsletters)',
            'Prompts and Code Interpreter for Data Analysis and Financial Spreadsheets',
            'AI for Project Management, OKR Creation, and Technical Documentation',
            'Creating Dynamic Prompts and Templates for Continuous Use'
          ]
        },
        {
          nome: 'Ecosystem, APIs, and Customization',
          topicos: [
            'Building Custom GPTs for Specific Roles in Your Company',
            'The First Integration with the OpenAI or Anthropic API',
            'No-Code Automations with AI (Make, Zapier, n8n + LLMs)',
            'Compound Workflows: Chaining Multiple AI Calls in the Backend',
            'Artifacts (Claude) and Canvas (ChatGPT): AIs That Generate Interfaces and Docs in Real-Time'
          ]
        },
        {
          nome: 'Advanced Connectivity: The Power of MCP',
          topicos: [
            'MCP (Model Context Protocol): Anthropic\'s Universal Connectivity Standard',
            'How Claude Desktop Works + Access to the File System (Local MCP)',
            'Integrating Claude with Notion via MCP: AI Reading and Editing Your Digital Brain',
            'Popular MCP Connectors: GitHub, Slack, Google Drive, and Their Applications',
            'Agentic AI Tools and Tool Use (Function Calling)',
            'Accessing Databases: AI Querying SQL and Postgres Directly via MCP'
          ]
        },
        {
          nome: 'Vibe Coding, Autonomous Agents, and Terminal',
          topicos: [
            'AI for Basic Programming: How to Request Code Without Knowing How to Program (Vibe Coding)',
            'Basic Multi-Agent Systems: Splitting Complex Tasks Among AIs',
            'AI-Powered IDEs: Workflows in Cursor and Windsurf',
            'Claude Code and Terminal Agents: Giving the AI Control of the Command Line',
            'AI Coding Assistants: How to Review, Test, and Validate Code Generated by the Machine',
            'Advanced Autonomous Agents (Devin, AutoGPT, BabyAGI): What is Real vs Hype'
          ]
        }
      ]
    },
    {
      slug: 'founder-ia-automacao',
      nome: 'AI & Automation for Founders',
      emoji: '🤖',
      parent: 'founder-solo',
      whyStart: 'In 2026, a solo founder with a well-configured AI stack competes with 10-person teams. Those who do not master AI as leverage are running with lead in their shoes.',
      descricao: 'LLMs, AI Agents, process automation, and building native AI products for the 1-person founder.',
      contexto: `Focus: AI as an operational force multiplier and as a product.
Mandatory approach:
- How to use LLMs (GPT-4o, Claude, Gemini) as a decision copilot.
- Building AI Agents to automate internal workflows.
- Native AI products: what is and what is not a good idea.`,
      ementa: [
        'The Solo Founder\'s AI Stack in 2026: A Complete Map',
        'Advanced Prompt Engineering for Business Tasks',
        'AI Agents with LangChain and CrewAI: Fundamental Concepts',
        'Outreach and CRM Automation with AI (Clay, Apollo + GPT)',
        'Building Products with the OpenAI and Anthropic APIs',
        'RAG (Retrieval-Augmented Generation): Private Knowledge Bases',
        'Vibe Coding: Using Cursor and GitHub Copilot to Be 10x Faster',
        'AI for Customer Support: Zaps, n8n, and Smart Chatbots',
        'Fine-tuning vs Prompting: When Each Approach Is Worth It',
        'Automating Content Marketing with AI (Without Looking Like a Robot)',
        'AI Tools for Financial Analysis and Churn Prediction',
        'Data Privacy When Using Third-Party LLMs (LGPD + AI)',
        'Make (Integromat) and n8n: No-Code Automations for Growth',
        'Monitoring and Evaluating the Quality of Your AI Pipelines',
        'The Augmented Founder: When to Delegate to AI vs to Humans'
      ]
    },
    {
      slug: 'founder-marketing-distribuicao',
      nome: 'Marketing, Positioning & Distribution',
      emoji: '📣',
      parent: 'founder-solo',
      whyStart: 'The biggest mistake of technical founders: building an amazing product that nobody knows exists. Distribution is not what you do after building — it is what you plan before. Without an acquisition channel that works without you, the business is a disguised job.',
      descricao: 'From consumer psychology to the growth engine: positioning, branding, organic channels, growth loops, and scalable distribution for solo founders in 2026.',
      contexto: `Focus: building demand and audience as permanent assets, not one-off campaigns.

Mandatory approach:
- Always start from the mechanism: "why do people buy?" before talking about tools or channels.
- JTBD, Kahneman, Cialdini: explain the psychological principle before the application.
- Differentiate content strategy (the map) from content production (the execution).
- For each channel: explain the cost, the growth ceiling, and when to stop.
- Growth Hacking: demystify it. It is cheap and fast experimentation — teach the method, not the myth.
- Question romanticisms: "Does Building in Public work for every type of product? Why not?"`,
      fases: [
        {
          nome: 'Why People Buy: Psychology and Decision Mechanisms',
          topicos: [
            'Marketing vs Advertising vs Publicity: The Three Things Founders Mix Up All the Time',
            'Jobs To Be Done (JTBD): The Customer Never Buys the Product — They Hire a Solution for a Progress',
            'Kahneman\'s System 1 and System 2: How Decisions Happen Emotionally Before Being Rationalized',
            'Psychology of Social Proof, Authority, and Reciprocity (Cialdini): The Underlying Neural Mechanism',
            'Value Perception vs Real Price: Why Cheap Looks Suspicious and Expensive Looks Superior',
            'The Paradox of Choice (Barry Schwartz): Fewer Options Sell More — The Science of Choice Overload',
            'Anchoring, Decoy, and Framing: How Price Presentation Alters Value Perception',
            'Halo Effect: How the First Impression of a Product Contaminates All Subsequent Perceptions',
            'Neuromarketing: What the Real Data Says About Consumption (and What Is Salesman Myth)',
            'Consumer Behavior in the Digital Era: Fragmented Attention, Short Decision Cycles, and the Doom Scroll'
          ]
        },
        {
          nome: 'Positioning, Branding, and Category Design',
          topicos: [
            'Strategic Positioning: Occupying a Mental Category Before Competing on Price',
            'Branding for Solo Founders: It\'s Not a Logo — It\'s Systematic Perception Management',
            'The 4 Ps of Marketing: The Original Framework, Its Limitations, and What Replaced Each One',
            'Blue Ocean Strategy (Kim & Mauborgne): How to Create Markets Without Direct Competition',
            'Category Design: Inventing a Category vs Competing in an Existing One — When Each Makes Sense',
            'Structural Storytelling for Founders: How Joseph Campbell and Donald Miller Apply to SaaS',
            'Conversion Copywriting: Headlines, CTAs, and Landing Pages — Response Engineering, Not Pretty Writing',
            'Copy Frameworks: PAS (Problem-Agitation-Solution), AIDA, and FAB — The Mechanism Behind Each One',
            'Personal Branding as a Distribution Channel: You as Your Own Permanent Media',
            'Image Crisis Management for Founders: What to Do When Twitter Decides You Made a Mistake',
            'Solo Brand Architecture: When to Separate Personal Brand and Product Brand'
          ]
        },
        {
          nome: 'Organic Channels and Asynchronous Distribution',
          topicos: [
            'Strategic Content Marketing: The Difference Between Having a Content Strategy and Producing Content',
            'Technical and Content SEO for SaaS: How a Search Engine Works Before Talking About Keywords',
            'Conversational SEO and AEO (Answer Engine Optimization) for Perplexity, ChatGPT, and Google AI Overviews',
            'Building in Public: When Radical Transparency Becomes an Acquisition Channel — and When It Doesn\'t Work',
            'Newsletter as a Distribution Asset: From Zero to 10k Readers Without Paying For It',
            'Podcast as an Authority Channel: How to Start Without Radio Infrastructure',
            'LinkedIn as a B2B Acquisition Channel: The Algorithm, the Format, and What Actually Engages',
            'Twitter/X: Building a Technical Audience — The Difference Between Going Viral and Accumulating',
            'YouTube and Long-form Video for SaaS: Video SEO and Content That Doesn\'t Age',
            'Short-form Video (Reels, Shorts, TikTok): How to Adapt Technical Content for 60-Second Formats',
            'UGC (User Generated Content): When the Customer Themselves Becomes a Creator and Distributor',
            'Presence in Marketplaces: AppSumo, Capterra, G2, and Product Hunt — The Definitive 2026 Guide'
          ]
        },
        {
          nome: 'Growth, Viral Loops, and Organic Scale',
          topicos: [
            'The Anatomy of an Acquisition Funnel for Solo Founders: AARRR Without Corporate Complexity',
            'Growth Loops vs Linear Funnel: Why Loops Scale and Funnels Have a Ceiling',
            'Product-Led Growth (PLG): Designing the Product to Be Its Own Acquisition Channel',
            'Virality Loop and K-Factor: How to Calculate and Design Organic Growth Through Referrals',
            'North Star Metric: Finding the Single Metric That Sums Up the Value Delivered by the Product',
            'Cold Email with AI Personalization: What Still Works in 2026 and Why',
            'Partnerships and Co-Marketing: How Two Solo Founders Multiply Each Other\'s Audience',
            'Affiliate Marketing and Automated Referral Programs: Leveraging Influence with Incentive Alignment',
            'Low-Cost Retargeting: Google and Meta with a Micro Budget for Those Without Growth Capital',
            'Organic Press and PR: How to Get Media Coverage Without a PR Agency',
            'Building Community (Discord, Circle, WhatsApp): When Community Is a Channel — and When It Is a Distraction',
            'Marketing Analytics for Founders: How to Set Up an Acquisition Dashboard Without Getting Lost in Vanity Metrics'
          ]
        }
      ]
    },
    {
      slug: 'founder-vendas-receita',
      nome: 'Sales, Revenue & Pricing',
      emoji: '💰',
      parent: 'founder-solo',
      whyStart: 'If it doesn\'t generate revenue, it\'s a hobby. Charging from day 1 is the most honest test of whether you are solving a real problem. The founder who doesn\'t know how to sell depends on luck — and luck has a very high churn rate.',
      descricao: 'From the first conversation to a repeatable pipeline: The Mom Test, sales methodology, strategic pricing, and building healthy recurring revenue for the solo founder.',
      contexto: `Focus: real revenue — how to charge, how much to charge, and how to sell being the sole salesperson (sometimes introverted).

Mandatory approach:
- Start with The Mom Test: the founder's most expensive mistake is confusing flattery with purchase intent.
- For each methodology (SPIN, BANT, MEDDIC): explain the problem it solves before applying the script.
- Be honest about rejection: it is not personal, it is data. Reframe the game mentally.
- Pricing is not just a number: it is positioning, value signaling, and filtering out the wrong customer.
- PLG and Sales-Led are not rivals — teach when each approach makes sense and how to combine them.`,
      fases: [
        {
          nome: 'The First Sale: Validating That Someone Actually Pays',
          topicos: [
            'The Mom Test (Rob Fitzpatrick): How to Ask Questions That Do Not Lie to You — the Most Underestimated Book in Startups',
            'The Difference Between Interest, Purchase Intent, and Payment: How to Distinguish in Real-Time',
            'Ideal Customer Profile (ICP): Who They Are, Who They Definitely Are Not, and Why Rejecting the Wrong Customer Saves the Business',
            'How to Make the First Sale as a Founder — Without a Team, Without a Script, Sometimes Without a Finished Product',
            'Demos That Convert: Product Demo Structure, What Never to Do, and How to End with a CTA',
            'Copywriting for Landing Pages, Cold Emails, and Sales Proposals: Response Engineering Before Pretty Words',
            'SaaS Conversion Funnel: From Visit to MRR — Where Founders Lose the Customer (and Why)',
            'Handling Rejections: Reframing as Strategic Data, Not Personal Failure',
            'Discovery Call: The Right Questions Before Presenting Anything — Diagnosis Before Prescription',
            'Sales Proposals That Close: Structure, Language, and What Never to Include in the PDF'
          ]
        },
        {
          nome: 'Sales Methodology and Repeatable Pipeline',
          topicos: [
            'SPIN Selling (Neil Rackham): Situation, Problem, Implication, and Need-payoff — The Logic Behind It',
            'Lead Qualification: BANT (Budget, Authority, Need, Timeline) and MEDDIC for the Solo Context',
            'Overcoming Objections: The 10 Most Common in SaaS and How to Break Each One Without Sounding Manipulative',
            'Contract Negotiation: How Not to Give a Discount Without Losing the Customer — the Psychology of the Anchor and Silence',
            'Value Proposition: How to Present ROI Without Sounding Like a Flea Market Salesman or a PowerPoint Consultant',
            'Sales Pipeline with a Solo CRM: Notion, Free HubSpot, or Pipedrive — Which to Choose and How to Keep It Warm',
            'Structured Follow-up: The Timing, Frequency, and Tone That Keeps the Lead Warm Without Being Annoying',
            'Enterprise Sales as a Solo Founder: When and How to Go Upmarket Without Dying in the Process',
            'Closing: Closing Techniques Without Abusive Pressure — Hard Close, Trial Close, and Next Step Close',
            'Win/Loss Analysis: Why You Lost (or Won) and What This Data Says About Your Positioning and ICP'
          ]
        },
        {
          nome: 'Strategic Pricing and Revenue Models',
          topicos: [
            'The Psychology of Pricing: Why the Number You Choose Communicates Before It Is Calculated',
            'Value-Based Pricing: Charging for the Value Generated for the Customer, Not the Cost of Production',
            'Freemium vs Trial vs Paid from Day 1: The Economic Logic Behind Each Model',
            'Usage-Based Pricing: Charging for Usage Like AWS — When It Works and When It Destroys Predictability',
            'Annual Plans: How to Convence the Customer to Pay Yearly (and the Impact on Cash Flow)',
            'Pricing Pages That Convert: Plan Hierarchy, Value Anchoring, and the Decoy Effect in Practice',
            'When and How to Increase Prices Without Losing Your Customer Base',
            'PLG vs Sales-Led: When to Let the Product Sell and When You Need to Be the Salesperson',
            'Bundling and Unbundling: The Art of Packaging Features to Maximize Perceived Value'
          ]
        },
        {
          nome: 'Recurring Revenue, Retention, and Expansion',
          topicos: [
            'MRR, ARR, and the Real Math of SaaS: What Each Number Hides and Reveals',
            'Churn Rate: Why Growing Without Retaining Is Like Filling a Leaky Bucket — and How to Calculate the Business Ceiling',
            'Net Revenue Retention (NRR) Above 100%: The Only Metric That Truly Proves the Product Works',
            'Upselling and Cross-selling: Expanding Revenue Without Acquisition Costs',
            'Customer Success as Churn Prevention: The Difference Between Reactive Support and Proactive CS',
            'Churn Recovery: How to Reactivate Customers Who Canceled — Win-Back Campaigns and Timing',
            'Revenue Cohort Analysis: Reading Longitudinal Financial Health, Not Just the Month\'s MRR',
            'Expansion to Enterprise: Annual Contracts, SLAs, and What Changes in the Sales Process',
            'Referral Sales: The Channel That Doesn\'t Age and Has CAC Close to Zero',
            'Building a Predictable Revenue Model: Combining PLG, Sales, and Expansion into a System'
          ]
        }
      ]
    },
    {
      slug: 'founder-dev-arquitetura',
      nome: 'Development & Architecture',
      emoji: '⚙️',
      parent: 'founder-solo',
      whyStart: 'Iteration speed is your only competitive advantage against large corporations. Simple architecture beats complex architecture.',
      descricao: 'Technical decisions optimized for speed, low maintenance, and cheap scalability in 2026.',
      contexto: `Focus: Pragmatic engineering. Tools that reduce friction.
Mandatory approach:
- Monoliths vs Microservices: Choose pragmatism.
- BaaS (Supabase/Firebase) as a strength multiplier.
- Vibe Coding and AI as a development copilot.`,
      ementa: [
        'The Solo Founder\'s Architecture (Monoliths and BaaS)',
        'Choosing the Tech Stack: Productivity vs Hype in 2026',
        'CI/CD and Frictionless Continuous Deployment (GitHub Actions + Vercel)',
        'Database Management and Simplified Migrations',
        'Infrastructure Automation with Vercel, Railway, and Fly.io',
        'Automated Testing: What Really Matters for 1 Dev',
        'Dealing with Technical Debt When You Are the Only Dev',
        'Supabase from Scratch to Advanced: Auth, RLS, Storage, and Edge Functions',
        'Serverless and Edge Computing: When to Use and When to Avoid',
        'Cheap Observability: Logs, Alerts, and Tracing for Solo SaaS',
        'Application Security: The Non-Negotiable Minimum Checklist',
        'API Design for Products That Will Scale (REST vs tRPC vs GraphQL)',
        'WebSockets and Real-time: When the User Needs Live Feedback',
        'Monorepos with Turborepo: Managing Multiple Solo Products',
        'Feature Flags: Safe Launches and Immediate Rollbacks',
        'Billing and Payments: Stripe from Scratch, Webhooks, and Subscription Management',
        'Multi-tenancy: Architecture for SaaS Serving Multiple Customers',
        'Smart Caching: Redis, CDN, and Strategies to Scale Without Cost'
      ]
    },
    {
      slug: 'founder-produto-ux',
      nome: 'Product Manager — From Zero to Advanced',
      emoji: '🎯',
      parent: 'founder-solo',
      whyStart: 'The PM is the CEO of the product. They don\'t code, they don\'t design, they don\'t sell — but they are responsible for everything. Those who master PM can turn any idea into a product that people pay to use.',
      descricao: 'Discovery, prioritization, metrics, UX/design, and product strategy — from idea to scaling product.',
      contexto: 'The student is a solo founder who needs to wear the PM hat. Focus on the bridge between user, business, and engineering. When citing frameworks, indicate where they came from (e.g., Teresa Torres, "Continuous Discovery Habits", 2021).',
      fases: [
        {
          nome: 'Phase 1 — Foundations: What Is Product and What Is the PM\'s Role',
          topicos: [
            'The PM Role: The Bridge Between Engineering, UX, and Business — Without Formal Authority',
            'What Is a Digital Product — The Difference Between Product, Feature, and Project',
            'Product Discovery vs Product Delivery — Where Most Companies Make Mistakes',
            'Jobs-to-be-Done (JTBD): Understanding What the User Actually "Hires" the Product to Do',
            'User Interviews: How to Ask the Right Questions Without Contaminating the Answer',
            'The Problem with Premature Solutions — Confirmation Bias in Product Management',
            'Personas vs Jobs: When Each Model Helps and When It Gets in the Way',
            'Product Life Cycle: Introduction, Growth, Maturity, and Decline',
            'Platform Products vs End-User Products — Different Logic and Dynamics',
            'The Product Vision Document (Simplified PRD): What It Needs to Have',
            'Inception: How to Align the Entire Team at the Beginning of a Product',
            'MVP: What It Is, What It Isn\'t, and Why Most Do It Wrong'
          ]
        },
        {
          nome: 'Phase 2 — Intermediate: Prioritization, Metrics, and the Product Cycle',
          topicos: [
            'Prioritization Frameworks: RICE, Kano, MoSCoW — When to Use Each',
            'Backlog Management: The Difference Between a Living Backlog and a Graveyard of Ideas',
            'Strategic Roadmap: Now/Next/Later vs Date-Based Roadmap',
            'North Star Metric: Finding the Single Metric That Sums Up the Value Delivered',
            'AARRR (Pirate Metrics): Acquisition, Activation, Retention, Revenue, and Referral',
            'Cohort Analysis and Churn: How to Read Real Product Health in Data',
            'A/B Testing and Continuous Experimentation: Hypotheses, Samples, and Significance',
            'Opportunity Solution Tree (Teresa Torres, 2021): Mapping Opportunities Without Bias',
            'Continuous Discovery Habits: Weekly Research Routine with Real Users',
            'OKRs for Product: Aspirational Goals vs Operational Tasks',
            'Stakeholder Management: Aligning Leadership, Sales, and Engineering Without Wars',
            'Go-to-Market of New Features: How to Launch Without Generating Confusion',
            'Heatmaps and Session Recordings: Reading the User\'s Silent Behavior',
            'Feedback Loops: NPS, CSAT, and CES — What Each Actually Measures',
            'Quantitative + Qualitative Data: Why Neither Alone Solves the Problem',
            'Unit Economics Applied to Product: CAC, LTV, and Payback Period'
          ]
        },
        {
          nome: 'Phase 3 — Advanced: UX, Design, and Product Strategy in 2026',
          topicos: [
            'Product-Led Growth (PLG): Letting the Product Be the Main Acquisition Channel',
            'Growth Loops: Building Sustainable Viral Cycles — Viral, Paid, and Content Loops',
            'Pricing Strategy: Freemium, Usage-Based, Value-Based — The Logic of Each Model',
            'Product Ops: Scaling the Product Function When the Team Grows',
            'Wireframing and Rapid Prototypaging with Figma and v0.dev',
            'Design Systems: Tokens, Components, and Visual Consistency as a Competitive Advantage',
            'Nielsen\'s Heuristics: The 10 Principles Every PM Needs to Know How to Evaluate',
            'Onboarding: Engineering the "Aha!" Moment — Reducing Friction in Activation',
            'Micro-interactions and Feedback Animations: When UX Delights and When It Distracts',
            'Accessibility (a11y and WCAG): The Non-Negotiable Minimum in Product Quality',
            'Dark Patterns: What Never to Do and How to Identify in Competitors',
            'The Art of Saying No: How to Reject Features Without Losing Allies',
            'AI-First Product Management: Managing Non-deterministic AI Features',
            'Evaluation-Driven PM: How to Measure Output Quality of Language Models',
            'Agents as a Product: UX for Autonomous Systems and Interactions with AI Agents',
            'Competitive Analysis: Frameworks to Map Competitors Without Bias',
            'API as a Product: When Developers Are Your Main Customers',
            'International Product: Localization, Cultural Adaptation, and i18n Traps',
            'Ethical Product Design: PM Responsibility for Social Impact and Dark Patterns',
            'Churn Analysis: Why Users Disappear and How to Anticipate Before Losing Them'
          ]
        }
      ]
    },
    {
      slug: 'founder-financas-fundraising',
      nome: 'Finance & Fundraising',
      emoji: '🏦',
      parent: 'founder-solo',
      whyStart: 'Lack of cash kills startups. Knowing when to bootstrap and when to raise money is a fundamental decision.',
      descricao: 'Cash management for founders, Bootstrapping vs VC, financial modeling, and strategic fundraising.',
      contexto: `Focus: Financial survival and smart capital allocation.
Mandatory approach:
- Unit Economics and Burn Rate.
- The VC myth vs the Bootstrapping reality in 2026.`,
      ementa: [
        'Bootstrapping vs Venture Capital (VC): Pros, Cons, and Trade-offs',
        'Calculating Runway and Managing Burn Rate',
        'Essential Unit Economics: CAC, LTV, and Payback Period',
        'How to Prepare a Precise and Honest Pitch Deck',
        'Equity Math and Dilution in Investment Rounds',
        'Liquidity Pockets and Personal Risk Management for the Founder',
        'Revenue-Based Financing',
        'Grants and Non-Dilutive Funding for Startups',
        'Accelerators: YC, Distrito, and Others — Is It Worth Applying?',
        'Basic Financial Modeling: P&L, Cash Flow, and Projections',
        'Taxes for Founders: Simples Nacional vs Lucro Presumido (Brazilian Tax Context)',
        'Separating Personal and Business Finances (and Why It Is Critical)',
        'Renegotiating Vendor Contracts in Times of Crisis',
        'Pricing to Scale: When to Increase Prices and How to Do It',
        'Crowdfunding and Pre-sales as Validation and Cash Strategies',
        'SAFE and Convertible Notes: Modern Fundraising Instruments',
        'Investor Due Diligence: What They Will Ask For and How to Prepare'
      ]
    },
    {
      slug: 'founder-gestao-produtividade',
      nome: 'Time Management & Productivity',
      emoji: '⏱️',
      parent: 'founder-solo',
      whyStart: 'You have the same 24 hours as large teams. Where you focus determines whether the business moves forward or spins in circles.',
      descricao: 'Extreme productivity frameworks, mental health, and focus for the solo founder in 2026.',
      contexto: `Focus: Self-management. The psychology of being solely responsible for success and failure.
Mandatory approach:
- How to avoid structural burnout.
- Merciless prioritization (Eisenhower Matrix, Timeboxing).
- AI as low-cost delegation.`,
      fases: [
        {
          nome: 'Phase 1: Physical Foundations and Deep Focus',
          topicos: [
            'Timeboxing and Deep Work in Practice',
            'The Art of Merciless Prioritization: What Can Only You Do?',
            'Context Switching: The Silent Enemy of Productivity',
            'Sleep, Exercise, and Cognition: The Science Behind High Performance',
            'Fast Decision-Making with Incomplete Data (Good Enough)'
          ]
        },
        {
          nome: 'Phase 2: Mental Health and Solo Survival',
          topicos: [
            'Burnout Prevention: Non-Negotiable Routines and Healthy Boundaries',
            'Dealing with Isolation and the Loneliness of the Solo Founder',
            'Dopamine Detox and Sustainable Focus in a World of Notifications',
            'Vanity Metrics vs Actionable Metrics: Where to Focus Energy'
          ]
        },
        {
          nome: 'Phase 3: The Digital Brain (Personal Systems)',
          topicos: [
            'The Founder\'s Note-Taking System: Obsidian, Notion, and Second Brain',
            'Email Management and Asynchronous Communication to Avoid Slavery',
            'Strategic Journaling for Founders: Mental Clarity and Direction'
          ]
        },
        {
          nome: 'Phase 4: Rituais, Goals, and Tracking',
          topicos: [
            'The Founder\'s Ideal Week: How to Structure Time Blocks by Energy',
            'Personal OKRs: How to Set and Track Quarterly Goals',
            'Weekly and Monthly Review Process: High-Performance Rituals'
          ]
        },
        {
          nome: 'Phase 5: Extreme Delegation and Leverage with AI',
          topicos: [
            'Low-Cost Delegation: Virtual Assistants, Freelancers, and AI',
            'Outsourcing Tasks with High Cognitive Cost but Low Complexity to AI'
          ]
        }
      ]
    },
    {
      slug: 'founder-juridico-lgpd',
      nome: 'Legal, Data Privacy & Contracts',
      emoji: '⚖️',
      parent: 'founder-solo',
      whyStart: 'A lawsuit can destroy everything you have built. The legal basics are your armor.',
      descricao: 'Simplified legal compliance, intellectual property protection, and terms of service in 2026.',
      contexto: `Focus: Legal risk mitigation without unnecessary complication.
Mandatory approach:
- LGPD/GDPR in practice for SaaS.
- Terms of Use and Privacy Policies that protect the founder.`,
      ementa: [
        'LGPD Basics for Developers and Founders',
        'Waterproof Terms of Use and Privacy Policy',
        'Trademark Registration and Intellectual Property: How and When to Do It',
        'Contracts with Freelancers: Ensuring Rights Over the Work',
        'Creating a Legal Entity: CNPJ, LLC, LDA, and Global Options',
        'Receiving International Payments and Taxation',
        'Basic Asset Protection for Founders',
        'GDPR for Brazilian Founders with European Customers',
        'Non-Disclosure Agreement (NDA): When to Require and How to Draft It',
        'Cookie Management and Consent: Plugin vs Custom Solution',
        'Intellectual Property in Employment and Freelance Contracts',
        'Refund Policy and Chargeback: Prevention and Dispute Management',
        'Open Source: Licenses, Risks, and How to Use Without Harm',
        'Limited Liability and When the Corporate Veil Does Not Protect',
        'Arbitration vs Litigation: Resolving Disputes Without Long Lawsuits'
      ]
    },
    {
      slug: 'founder-mindset-psicologia',
      nome: 'Mindset & Founder Psychology',
      emoji: '🧠',
      parent: 'founder-solo',
      whyStart: 'The biggest obstacle for a solo founder is not the market, the code, or the money — it is the mind. Mastering psychology is the meta-skill of everything.',
      descricao: 'The psychology, beliefs, and mental patterns that separate founders who make it from those who give up.',
      contexto: `Focus: The internal dimension of entrepreneurship.
Mandatory approach:
- Imposter Syndrome and how to overcome it.
- Long-term thinking vs immediate gratification.
- Learning from failure without destroying self-esteem.`,
      ementa: [
        'Imposter Syndrome: Why Every Founder Feels It and How to Manage It',
        'Growth Mindset in Daily Practice',
        'Making Decisions with Cognitive Biases: How to Recognize and Mitigate',
        'The Founder\'s Emotional Cycle: Euphoria, Valley of Death, and Recovery',
        'Applied Stoicism to Entrepreneurship: Marcus Aurelius as a Mentor',
        'Probabilistic Thinking: How Successful Founders Assess Risk',
        'Identity and the Danger of Being Your Business (Identity Enmeshment)',
        'How to Deal with Public Failure and Learn Without Shame',
        'Calibrated Ambition: How to Dream Big and Act in the Real World',
        'Comparison and FOMO: How to Not Destroy Yourself Watching Others\' Success',
        'Perseverance vs Stubbornness: How to Know the Difference in Real-Time',
        'Founder Communities: The Importance of Not Being Alone',
        'Separating Work from Identity: Hobbies, Family, and Mental Health',
        'Therapy and Coaching for Founders: Investment, Not Weakness',
        'The Role of Ego in Entrepreneurship: Fuel or Saboteur?'
      ]
    },
    {
      slug: 'design',
      nome: 'Visual Design & UX',
      emoji: '◑',
      parent: 'founder-solo',
      layout: 'canvas',
      widget: 'DesignPreview',
      whyStart: 'The best algorithm in the world fails if the user interface (UX) is poor. Design is not aesthetics — it is the logic of how humans perceive and interact with systems.',
      descricao: 'Hierarchy, typography, gestalt, and user-centered design — from perceptual foundations to AI-native design.',
      contexto: 'Focus: structural design principles — hierarchy, gestalt, visual perception. Mandatory approach: explain the perceptual or cognitive principle behind each design decision. Only then: ask the student to critique a real design.',
      ementa: [
        'Gestalt Laws Applied to Interfaces',
        'Color Theory and Contrast',
        'Typography and Typographical Scale',
        'Spacing and Visual Hierarchy',
        'UI vs UX: The User Experience',
        'Nielsen\'s Heuristics',
        'Design Systems: Tokens, Components, and Documentation',
        'Prototyping: From Sketch to Interactive Figma',
        'Usability Testing: Methods and Analysis',
        'Responsive and Mobile-First Design',
        'Accessibility (WCAG): Design for Everyone',
        'Micro-interactions and Feedback Animations',
        'Dark Patterns: What Never to Do',
        'Onboarding Design: Reducing Friction',
        'Motion Design: Movement with Purpose',
        'Design for AI: Conversational and Probabilistic Interfaces',
        'Machine Experience (MX): Optimizing for Humans and Agents',
        'Explainable UX: Transparency in AI Decisions',
        'Adaptive UI: Interfaces That Adjust to the User\'s Context',
        'Multimodal Design: Voice, Gesture, and Touch Integrated',
        'Calm Design: Reducing Cognitive Overload',
        'Emotional Design: Microcopies That Build Connection',
        'UX Writing: Writing for Interfaces',
        'Information Architecture: Organizing Complex Content',
        'Design Sprint: Prototyping in 5 Days (Google Ventures)',
        'Atomic Design: Atoms, Molecules, and Organisms',
        'Cognitive Psychology Applied to UX: Hick\'s, Fitts\'s, and Miller\'s Laws',
        'Dashboard Design and Data Visualization',
        'Form Design: Reducing Abandonment',
        'Digital Sustainability: Eco-Conscious Design'
      ]
    },
    {
      slug: 'marketing-conceitual',
      nome: 'Marketing & Consumer Psychology',
      emoji: '📣',
      parent: 'founder-solo',
      whyStart: 'Before any tool or tactic, you need to understand the mechanism: why people buy. Those who skip this step learn to push buttons without knowing what they are doing — and when the campaign fails, they don\'t know why.',
      descricao: 'Foundations of marketing: consumer psychology, positioning, and the logic behind every purchase decision.',
      contexto: `Focus: the fundamental mental models of marketing. Teach the WHY before the HOW.

Mandatory approach:
- For each framework (4 Ps, JTBD, etc.): explain the problem it solves and where it fails before applying it.
- Consumer psychology is not manipulation — teach with ethics and real mechanisms.
- Branding is not aesthetics; it is perception management. Teach the difference.`,
      fases: [
        {
          nome: 'The Mechanism of the Purchase Decision',
          topicos: [
            'Marketing vs Advertising vs Publicity: Distinctions That Matter for Founders',
            'Jobs To Be Done (JTBD): The Customer Buys Progress, Not the Product',
            'Consumer Psychology: The Neural Triggers That Precede Purchase',
            'Kahneman\'s System 1 and System 2: How Decisions Happen Before Reason',
            'Value Perception vs Price: Why Cheap Looks Suspicious',
            'The Paradox of Choice: Fewer Options Sell More (Barry Schwartz)',
            'Behavioral Economics Applied to Pricing: Anchoring, Decoy, and Framing',
            'The Psychology of Social Proof and Authority (Cialdini)'
          ]
        },
        {
          nome: 'Positioning and Brand Building',
          topicos: [
            'Market Positioning: Differentiation and Occupying a Mental Category',
            'Branding: Positioning, Identity, and Perception Management',
            'Blue Ocean Strategy: Creating Markets Without Competition (Kim & Mauborgne)',
            'The 4 Ps of Marketing: The Original Framework, Its Limitations, and What Comes After',
            'Structural Storytelling: Why Stories Sell More Than Logical Arguments',
            'The Halo Effect: How the First Impression Contaminates All the Rest',
            'Neuromarketing: The Neuroscience Behind Consumption (What the Data Actually Says)',
            'Image Crisis Management for Founders: What to Do When Everything Goes Wrong'
          ]
        },
        {
          nome: 'Distribution and Growth for Founders',
          topicos: [
            'The Anatomy of an Acquisition Funnel for Solo Founders',
            'Product-Led Growth (PLG): Letting the Product Be the Main Channel',
            'North Star Metric: The Single Metric That Sums Up the Value Delivered',
            'Organic Channels: SEO, Content, and Audience as Accumulable Assets',
            'Building in Public: Transparency as a Distribution Strategy',
            'Cold Email with AI Personalization: What Works in 2026',
            'Consumer Behavior in the Digital Era: Fragmented Attention and Short Cycles'
          ]
        }
      ]
    },
    {
      slug: 'founder-vendas',
      nome: 'Sales & Negotiation for Founders',
      emoji: '🤝',
      parent: 'founder-solo',
      whyStart: 'If it doesn\'t generate revenue, it\'s a hobby. Charging from day 1 is the most honest test of whether you are solving a real problem. A founder who doesn\'t know how to sell depends on luck to survive.',
      descricao: 'Repeatable sales process for solo founders: from the first customer to a scalable pipeline.',
      contexto: `Focus: selling being the sole salesperson — without a team, without a ready script, sometimes being introverted.

Mandatory approach:
- Always start with The Mom Test: the founder\'s most expensive mistake is thinking they are selling when they are only being flattered.
- For each methodology (SPIN, BANT): explain the problem it solves before applying it.
- Be honest about rejection: it is not personal, it is information. Reframe the game.`,
      fases: [
        {
          nome: 'The First Sale: Validating That Someone Pays',
          topicos: [
            'The Mom Test (Rob Fitzpatrick): How to Ask Questions That Do Not Lie to You',
            'The Difference Between Interest and Purchase Intent: How to Distinguish in Real-Time',
            'Ideal Customer Profile (ICP): Who They Are and Who They Definitely Are Not',
            'How to Make the First Sale as a Founder (Without a Team, Without a Script)',
            'Product Demos That Convert: Structure and What Never to Do',
            'Conversion Copywriting for Landing Pages and Founder Emails',
            'Handling Rejections: Reframing as Data, Not as Defeat'
          ]
        },
        {
          nome: 'Sales Process and Methodology',
          topicos: [
            'SPIN Selling: Situation, Problem, Implication, and Need-payoff',
            'Lead Qualification: BANT and MEDDIC in Solo Founder Practice',
            'The Discovery Process: Asking the Right Questions Before Presenting Anything',
            'Overcoming Objections: The 8 Most Common and How to Break Each One',
            'Contract Negotiation: How to Avoid Discounts and Still Close',
            'Value Proposition: How to Present ROI Without Looking Like a Flea Market Salesman',
            'Sales Pipeline with a Solo CRM: Notion, Linear, and Pipedrive for 1-Person Teams'
          ]
        },
        {
          nome: 'Scale and Recurring Revenue',
          topicos: [
            'PLG vs Sales-Led: When to Let the Product Sell and When You Need to Sell',
            'Value-Based Pricing: Charging for the Value Generated, Not the Cost',
            'Annual Plans: How to Convence the Customer to Pay Yearly',
            'Upselling and Cross-selling: Revenue Without Additional Effort',
            'MRR, ARR, and Churn: Understanding the Real Health of Revenue',
            'Net Revenue Retention Above 100%: The Metric That Proves the Product Works',
            'Churn Recovery: How to Reactivate Customers Who Canceled',
            'Win/Loss Analysis: Why You Lost and What to Do with That Data'
          ]
        }
      ]
    },
    {
      slug: 'visao-estrategica-inovacao',
      nome: 'Strategic Vision & Innovation',
      emoji: '🔭',
      parent: 'founder-solo',
      whyStart: 'Operating a business well is necessary, but insufficient. The founders who change the game do not compete — they create categories. This subject is about seeing what does not yet exist and having the intellectual courage to build.',
      descricao: 'From Zero to One to Antifragility: the mental models of frontier innovators who build monopolies, create categories, and shape the future.',
      contexto: `Focus: non-linear strategy and first-principles thinking applied to frontier businesses.

Mandatory approach:
- Always start from the mechanism before the application: "why does competition reduce profits?" before citing Thiel.
- Connect each mental model to a real decision the student can make today.
- Be skeptical: teach the limitations of each framework (Zero to One does not work for every type of business).
- Always ask: "what do you know that very few people know?" — this is the heart of all real innovation.
- Never romanticize entrepreneurship: real innovation is rare, risky, and expensive. Teach how to calculate the risk.`,
      fases: [
        {
          nome: 'Why Innovation Is Different From Improvement',
          topicos: [
            'The Fundamental Distinction: Incremental Innovation vs Category Innovation (Zero to One)',
            'Why Competition Is for Losers: Peter Thiel\'s Central Argument',
            'First-Principles Thinking: How Elon Musk Dismantles Accepted Truths',
            'The Paradigm of Disruptive Innovation: Clayton Christensen and Jobs-to-be-Done Theory',
            'Secrets and Counterintuitive Truths: What Do You Know That Nobody Else Does?',
            'The Problem with Incremental Growth: McKinsey\'s Horizon 1, 2, and 3',
            'Confirmation Bias in Strategy: Why Market Leaders Ignore Obvious Threats',
            'The Difference Between Being a Pioneer and Being a Category Founder'
          ]
        },
        {
          nome: 'Building Unfair Advantages',
          topicos: [
            'Network Effects and Metcalfe\'s Law: Value Grows Exponentially with Users',
            'Types of Moats: Competitive Advantages That Money Cannot Easily Buy',
            'Zero Marginal Cost: Why Software, Media, and AI Are Unique Businesses in History',
            'Leveraging Code and Media: Scaling Without Marginal Replication Cost (Naval)',
            'Amazon\'s Growth Flywheel: The Logic of Systems That Feed Themselves',
            'Permissionless Innovation: How Decentralized Technologies Redistribute Power',
            'The Engineering of Timing: Why "Too Early" Kills Just as Much as "Too Late"',
            'De Facto Monopolies: How Google, Meta, and Stripe Build Unreachable Positions',
            'Wealth vs Status: The Positive-Sum vs Zero-Sum Game (Naval Ravikant)',
            'The Success Paradox: How What Got You Here Can Stop You From Moving Forward'
          ]
        },
        {
          nome: 'Frontier Thinking and the AI Era',
          topicos: [
            'Asymptotic Thinking: Seeing the Theoretical Limit and Working Backward',
            'Second-Order Thinking: Consequences of the Consequences of Your Decisions',
            'Business Antifragility: Building Organizations That Gain from Chaos (Taleb)',
            'AI as an Infinite Scale Lever: The New Paradigm of Under-Resourced Founders',
            'Defensibility in an AI-First World: What Is Not Copyable When AI Commoditizes Everything',
            'Category Design: The Art of Creating a Market Instead of Competing in One',
            'The Logic of Technological Monopoly: When Dominating a Niche Is the Right Strategy',
            'Geopolitics and Macro Theses: How Global Structural Changes Create Windows of Opportunity',
            'Building the 1-Person Company with the Impact of 100: The AI-Augmented Founder',
            'Synthesis: Mapping Your Innovation Thesis — What Are You Betting On and Why'
          ]
        }
      ]
    },
    {
      slug: 'recrutamento-talentos',
      nome: 'Recruitment & Talent Management',
      emoji: '🎯',
      isCategory: false,
      parent: 'founder-solo',
      whyStart: 'A company is only as good as the people it can attract and retain. Hiring poorly is the most expensive mistake there is.',
      descricao: 'How to identify, attract, and retain exceptional people.',
      contexto: `Focus: recruitment as a competitive advantage — without corporate HR talk.

Mandatory approach:
- Base it on the practices of high-performance companies (Netflix, Stripe, SpaceX).
- No generic people management theory. Focus on difficult decisions and real trade-offs.`,
      ementa: [
        'The Real Cost of a Bad Hire (Exponential Impact)',
        'A-Players vs B-Players: The Difference Is Not Linear, It Is Exponential',
        'Steve Jobs\' Principle: A-Players Hire A-Players, B-Players Hire C-Players',
        'Structured Interviews vs "Feeling" Interviews (What Science Says)',
        'Work Samples and Case Studies: Testing Real Performance, Not Rhetoric',
        'Reference Checks That Work: The Questions Nobody Asks',
        'Hire Slow, Fire Fast: The Cost of Hesitating at Both Ends',
        'The "Bar Raiser" Concept (Amazon): Never Lowering the Standard',
        'Culture Fit vs Culture Add: The Danger of Homogeneity',
        'Talent Retention: Autonomy, Mastery, Purpose (Daniel Pink)',
        'Compensation Philosophy: Paying Above Market vs Equity',
        'The Termination Conversation: How to Do It with Respect and Dignity',
        'Continuous Performance Management vs Useless Annual Review',
        'The Talent Pipeline: Recruiting Before You Need To'
      ]
    },
    {
      slug: 'lideranca-execucao',
      nome: 'Leadership & Execution',
      emoji: '⚡',
      isCategory: false,
      parent: 'founder-solo',
      whyStart: 'Vision without execution is hallucination. Leading is about getting the team to deliver consistent results, not giving inspiring speeches.',
      descricao: 'How to lead in practice: delegation, difficult decisions, and accountability.',
      contexto: `Focus: operational leadership — the daily life of those managing people who need to deliver results.

Mandatory approach:
- Each concept must have a real application scenario ("you have a dev who delivers late, what do you do?").
- No empty motivational theory. Focus on decisions, trade-offs, and consequences.`,
      ementa: [
        'Effective Delegation: What to Delegate, How to Delegate, When Not to Delegate',
        'The Micro-management Problem: Signs That You Are Doing It',
        'Accountability vs Blame: Accountability Without a Culture of Fear',
        'One-on-Ones That Work: Ideal Structure and Frequency',
        'Radical Candor (Kim Scott): Caring Personally + Challenging Directly',
        'The Skill vs Will Matrix: 4 Types of Superordinates, 4 Approaches',
        'Situational Leadership (Hersey-Blanchard): Adapting Style to Context',
        'Group Decision Making: Consensus vs Command vs Consultative',
        'The Concept of "Disagree and Commit" (Bezos): Disagreeing and Executing',
        'Conflict Management: Confronting Tension Before It Explodes',
        'OKRs in Practice: What Works and What Fails (Real Lessons)',
        'Managing Up: How to Manage Your Boss',
        'Team Rituals: Stand-ups, Retrospectives, and Town Halls That Are Not a Waste of Time',
        'Remote Leadership: Trust, Asynchrony, and Distributed Culture',
        'Leader Burnout: Recognizing and Preventing Before Breaking'
      ]
    },
    {
      slug: 'cultura-organizacional',
      nome: 'Culture & Organizational Architecture',
      emoji: '🏗️',
      isCategory: false,
      parent: 'founder-solo',
      whyStart: 'Culture is not what is on the wall. It is what happens when the CEO is not looking. You design it or it appears on its own — and usually bad.',
      descricao: 'How to design a high-performance organizational culture with intent.',
      contexto: `Focus: culture as the operating system of the company, not as decoration.

Mandatory approach:
- Real use cases (Netflix Culture Deck, Valve Handbook, Spotify Model).
- Show the trade-offs of each cultural model. There is no perfect culture.`,
      ementa: [
        'What Culture Really Is: Declared Values vs Practiced Values',
        'The Netflix Culture Deck: Freedom and Responsibility (With Trade-offs)',
        'High-Performance Culture vs Toxic High-Performance Culture',
        'Amazon\'s Leadership Principles: The 16 Commandments (And What Works)',
        'Psychological Safety (Amy Edmondson): The #1 Factor of High-Performance Teams',
        'The Paradox of Transparency: Radical Transparency (Bridgewater) and Its Limits',
        'Flat vs Hierarchical Organizations: When Each Works',
        'Decision Speed vs Decision Quality: The Central Trade-off',
        'Onboarding as an Initiation Ritual: The First 90 Days',
        'Documentation vs Oral Tradition: How to Scale Tacit Knowledge',
        'Signs of Cultural Decay: Bureaucracy, Politics, and Performance Theater',
        'Conway\'s Law: Your Software Architecture Mirrors Your Organization',
        'Scaling Culture: What Changes When You Go from 10 to 100 People',
        'Corporate Rites of Passage: Promotion, Dismissal, and Celebration',
        'Cultural Anti-patterns: What Never to Do (With Real Examples)'
      ]
    }
  ]
};
