import { MateriaConfig } from '@/types';

export const realidadeHub: MateriaConfig = {
  slug: 'realidade-hub',
  nome: 'Ontology & Reality Mechanics',
  emoji: '🌌',
  isCategory: true,
  descricao: 'Fundamental physics, neuroscience of perception, and the cybernetics of action. The exact mechanics of how reality is constructed and how the observer can mathematically shape it.',
  children: [
    {
      slug: 'fisica-ontologia',
      nome: 'Physics, Chaos & Complex Systems',
      emoji: '⚛️',
      isCategory: false,
      parent: 'realidade-hub',
      whyStart: 'Before interacting with reality, you need to understand the absolute material rules that govern the universe.',
      descricao: 'The fundamental laws of the universe, from the limits of quantum mechanics to entropy and chaos.',
      contexto: 'Ensine a física de forma dura e precisa. Destrua mitos pseudocientíficos. O objetivo é causar deslumbramento através do rigor científico (como Carl Sagan ou Richard Feynman). Mostre a beleza matemática do caos e da probabilidade.',
      fases: [
        {
          nome: 'Level 1: Foundations of Matter & Classical Mechanics',
          topicos: [
            'O Método Científico e as Leis de Newton (O universo como relógio)',
            'Termodinâmica e Entropia (A seta do tempo e a inevitabilidade da degradação)',
            'Eletromagnetismo Básico: Luz e Informação'
          ]
        },
        {
          nome: 'Level 2: The Strange Quantum World',
          topicos: [
            'O Modelo Padrão de Partículas: Quarks, Léptons e Bósons',
            'Dualidade Onda-Partícula e o Experimento da Fenda Dupla',
            'O Problema da Medição e a Interpretação de Copenhague (Bohr)',
            'O Gato de Schrödinger: Superposição e Decoerência Quântica',
            'O Multiverso Quântico: Interpretação de Muitos Mundos (Hugh Everett)',
            'Entrelaçamento Quântico e a Não-Localidade (O Paradoxo EPR)'
          ]
        },
        {
          nome: 'Level 3: The Fabric of Space-Time',
          topicos: [
            'Relatividade Restrita: Dilatação do Tempo e a Constante "c"',
            'Relatividade Geral: A Gravidade como Curvatura',
            'Buracos Negros e Singularidades: Onde a física quebra'
          ]
        },
        {
          nome: 'Level 4: Chaos, Uncertainty & Non-Linear Systems',
          topicos: [
            'Princípio da Incerteza de Heisenberg: Os limites rígidos do conhecimento',
            'Teoria do Caos e o Efeito Borboleta na Prática',
            'Atratores Estranhos e Sistemas Dinâmicos Não-Lineares',
            'A Matemática da Natureza: Fractalidade e Auto-Semelhança',
            'O Teorema da Incompletude de Gödel e os limites da própria lógica'
          ]
        },
        {
          nome: 'Level 5: Emerging Theories & The Whole',
          topicos: [
            'Emergência: Como regras simples geram complexidade incompreensível',
            'Reducionismo vs Holismo: Os limites de quebrar as coisas em partes',
            'Teoria da Informação de Shannon e o Universo como Computação',
            'Princípio Holográfico: O Universo como projeção de informação'
          ]
        }
      ]
    },
    {
      slug: 'neuro-percepcao',
      nome: 'Neuroscience of Perception',
      emoji: '👁️',
      isCategory: false,
      parent: 'realidade-hub',
      whyStart: 'You have never experienced base reality. Everything you live is a simulation generated by your brain inside a dark box.',
      descricao: 'Predictive coding, the illusion of the "Self", and how the brain renders the world in real-time.',
      contexto: 'Foco na neurociência cognitiva contemporânea (Anil Seth, Karl Friston). Ensine que vemos com o cérebro, não com os olhos. O foco é provar que a experiência humana é uma alucinação controlada, abrindo espaço para a reprogramação cognitiva.',
      fases: [
        {
          nome: 'Level 1: The Sensory Hardware',
          topicos: [
            'Anatomia do Processamento Sensorial: Da física à biologia',
            'O Atraso Neural: Por que você vive permanentemente no passado',
            'Vias de Processamento Visual: Como o cérebro enxerga o que os olhos não veem'
          ]
        },
        {
          nome: 'Level 2: The Predictive Brain (Predictive Coding)',
          topicos: [
            'O Cérebro como Máquina de Inferência Bayesiana',
            'Processamento Top-Down vs Bottom-Up na Percepção Diária',
            'A Realidade como uma "Alucinação Controlada" (Anil Seth)',
            'O Princípio da Energia Livre e a Minimização da Surpresa (Karl Friston)'
          ]
        },
        {
          nome: 'Level 3: Evolutionary Filters & Biases',
          topicos: [
            'O Sistema Ativador Reticular Ascendente (SARA) e a Filtragem da Atenção',
            'Viéses Evolutivos: A máquina de detectar padrões (mesmo onde não existem)',
            'Ilusões de Ótica e Falhas Auditivas como Provas Algorítmicas',
            'Modelos Mentais como Algoritmos de Compressão da Realidade'
          ]
        },
        {
          nome: 'Level 4: The Illusion of the Self (The Observer)',
          topicos: [
            'A Rede de Modo Padrão (DMN): Onde habita a ansiedade e a ruminação',
            'A Ilusão da Identidade: O Ego como uma ferramenta evolutiva',
            'O Problema Difícil da Consciência (Qualia) e o Abismo Explicativo',
            'A Teoria do Espaço de Trabalho Global (Bernard Baars)'
          ]
        },
        {
          nome: 'Level 5: Hacking Perception',
          topicos: [
            'Neuroplasticidade Autodirigida: A mecânica de reescrever sinapses',
            'Estados Alterados e a Inibição do DMN (Dissolução Temporária do Ego)',
            'Linguagem como Limite Perceptivo (O Paradigma de Sapir-Whorf forte e fraco)'
          ]
        }
      ]
    },
    {
      slug: 'engenharia-realidade',
      nome: 'Cybernetics of Action (Co-creation)',
      emoji: '⚙️',
      isCategory: false,
      parent: 'realidade-hub',
      whyStart: 'The union between the physics of the environment and the neuroscience of perception results in the pragmatic ability to bend probability in your favor.',
      descricao: 'The scientific demystification of the "Law of Attraction". How to operate as an active observer using cybernetics, focus, and inertia.',
      contexto: 'Este é o ápice do Hub. Seja agressivo contra pseudociências e "O Segredo". Ensine "Lei da Atração" através da lente da Cibernética, Viés de Confirmação, Filtros de Atenção e Manipulação de Condições Iniciais no Teoria do Caos.',
      fases: [
        {
          nome: 'Level 1: Deconstructing Mysticism',
          topicos: [
            'O Mito de "O Segredo" vs Mecânica Real da Intenção',
            'Física Quântica não é Magia (Onde os esotéricos erram)',
            'Viés de Confirmação e Atenção Seletiva disfarçados de "Atração"'
          ]
        },
        {
          nome: 'Level 2: The Cybernetic Operator',
          topicos: [
            'O Conceito de "Frame" (Moldura) como a principal interface com o mundo',
            'Cibernética de Primeira e Segunda Ordem: O observador dentro do sistema',
            'Loops de Feedback Positivo e Negativo na construção de realidades diárias',
            'Autopoiese (Maturana e Varela): O indivíduo como um sistema que recria a si mesmo'
          ]
        },
        {
          nome: 'Level 3: Dealing with Inertia (The Physics of Action)',
          topicos: [
            'Homeostase Ambiental: Por que o universo e as pessoas lutam contra a mudança',
            'A Física da Ação: Vencendo a inércia e lidando com o atrito sistêmico',
            'O Paradoxo da Rendição: Como parar de resistir à entropia permite redirecioná-la',
            'A Mecânica do Desapego: Reduzindo a fricção e o comportamento de escassez'
          ]
        },
        {
          nome: 'Level 4: Probability Engineering & Attractors',
          topicos: [
            'Alinhamento do SARA: O poder neurobiológico da atenção concentrada obsessiva',
            'Engenharia de Condições Iniciais: Mudanças diárias que causam Efeitos Borboleta',
            'Engenharia de Atratores de Probabilidade: Como inclinar o caos a seu favor',
            'Sincronicidade Científica: A interseção da preparação extrema com a variação estatística'
          ]
        },
        {
          nome: 'Level 5: Advanced Systemic Maintenance',
          topicos: [
            'Visualização Ativa: Ensaio mental e o engajamento do córtex pré-motor',
            'O Colapso da Possibilidade: O ato da decisão irreversível como ponto de inflexão neural',
            'Epistemologia Pragmática: Avaliando suas crenças pela utilidade, não pela precisão absoluta'
          ]
        }
      ]
    }
  ]
};
