import { MateriaConfig } from '@/types';

export const tecnologiaHub: MateriaConfig = {
  slug: 'tecnologia-hub',
  nome: 'Computação & Arquitetura',
  emoji: '💻',
  isCategory: true,
  descricao: 'A ciência de construir o futuro. Da sintaxe básica da programação até a arquitetura de sistemas escaláveis.',
  children: [
    {
      slug: 'programacao-basica',
      nome: 'Programação Básica',
      emoji: '⌨️',
      parent: 'tecnologia-hub',
      whyStart: 'Antes de entender como um computador pensa matematicamente, você precisa aprender a falar o idioma dele. Sem isso, você não codifica.',
      descricao: 'Lógica, variáveis, loops e funções. O "Hello World" do seu futuro tecnológico.',
      contexto: `Foco: Fundamentos práticos da escrita de código.
O aluno é iniciante, ele precisa dominar a sintaxe básica de uma linguagem de programação (ex: JavaScript, Python) antes de se aprofundar na Ciência da Computação pesada.`,
      ementa: [
        // === EXISTENTES ===
        'O que é um Algoritmo: A Lógica da Vida Real',
        'Variáveis, Tipos de Dados e Operadores',
        'Estruturas Condicionais (If, Else, Switch)',
        'Estruturas de Repetição (For, While, Do-While)',
        'Funções e Escopo de Variáveis',
        'Trabalhando com Strings e Números',
        'Listas Básicas (Arrays/Vetores) e Iteração',
        'Objetos / Dicionários: Armazenando Dados Estruturados',
        'Tratamento de Erros Básico (Try/Catch)',
        'Leitura e Escrita Básica de Arquivos',
        'O que é uma API? Fazendo sua primeira requisição',
        'Ferramentas: Editor de Código (VSCode) e Terminal',
        // === NOVOS ===
        'Debugging: Como Ler Erros e Encontrar Bugs',
        'Tipos Primitivos vs Tipos por Referência',
        'Funções de Alta Ordem: Map, Filter e Reduce',
        'Closures e Callbacks: Funções dentro de Funções',
        'Introdução a Promises e Async/Await',
        'Manipulação do DOM: HTML + JavaScript na Prática',
        'Módulos e Imports: Organizando seu Código em Arquivos',
        'JSON: O Formato Universal de Troca de Dados',
        'Expressões Regulares (Regex) para Iniciantes',
        'Introdução a Tipagem Estática (TypeScript Básico)',
        'Linha de Comando (CLI): Navegação, Scripts e Automação',
        'Gerenciadores de Pacotes (npm, pip): Usando Código de Terceiros',
        'Ambiente de Desenvolvimento: .env, variáveis de ambiente',
        'Seu Primeiro Projeto Completo: Do Zero ao Deploy'
      ],
      layout: 'split',
      widget: 'CodeLab'
    },
    {
      slug: 'ciencia-computacao',
      nome: 'Ciência da Computação',
      emoji: '🧮',
      parent: 'tecnologia-hub',
      whyStart: 'Agora que você sabe programar, precisa aprender como os sistemas resolvem problemas matematicamente. Essa é a física da computação.',
      descricao: 'Matemática discreta, algoritmos de busca e estruturas de dados profundas.',
      contexto: `Foco: raciocínio computacional avançado e teoria.
O aluno já sabe programar o básico, agora ele precisa aprender otimização, Big O notation e resolver problemas algorítmicos difíceis.`,
      ementa: [
        // === EXISTENTES ===
        'Matemática Discreta: Álgebra Booleana e Lógica Proposicional',
        'Análise de Complexidade de Algoritmos (Big O Notation)',
        'Estruturas de Dados Básicas Profundas: Filas, Pilhas, Listas Ligadas',
        'Estruturas de Dados Avançadas: Árvores Binárias, Heaps, Hash Tables',
        'Teoria dos Grafos e Aplicações',
        'Recursão Avançada e Estratégias de Divisão e Conquista',
        'Algoritmos de Ordenação (Merge Sort, Quick Sort) e Busca',
        'Programação Dinâmica e Otimização de Memória',
        'Arquitetura de Computadores e Sistemas Operacionais',
        'Redes de Computadores: Modelo OSI e TCP/IP sob o capô',
        'Sistemas Numéricos, Bitwise e Representação de Dados em Memória',
        // === NOVOS ===
        'Teoria da Complexidade: P vs NP e Problemas Intratáveis',
        'Algoritmos Gulosos (Greedy) e Quando Falham',
        'Backtracking: Soluções por Tentativa e Erro Sistemático',
        'Tries e Suffix Trees: Busca Textual Eficiente',
        'Grafos Avançados: Dijkstra, A*, Bellman-Ford',
        'Tabelas de Dispersão (Hashing): Colisões e Estratégias',
        'B-Trees e Indexação de Bancos de Dados',
        'Teoria dos Autômatos e Linguagens Formais',
        'Compiladores: Lexing, Parsing e AST (Conceitos)',
        'Probabilidade e Estatística para Computação',
        'Álgebra Linear Computacional: Vetores e Matrizes',
        'Concorrência e Paralelismo: Threads, Locks e Race Conditions',
        'Gerenciamento de Memória: Stack vs Heap, Garbage Collection',
        'Criptografia Fundamental: Hashing, Simétrica e Assimétrica',
        'Teoria da Informação: Entropia e Compressão de Dados',
        'Computação Quântica: Conceitos Introdutórios (Qubits e Superposição)'
      ]
    },
    {
      slug: 'engenharia-software',
      nome: 'Engenharia de Software',
      emoji: '⚙️',
      parent: 'tecnologia-hub',
      whyStart: 'A teoria se torna inútil se você não consegue construir projetos reais de forma confiável e com outras pessoas.',
      descricao: 'Projetos reais, testes automatizados, Git, Clean Code e CI/CD.',
      contexto: `Foco: construção de software escalável, seguro e sustentável.
O aluno sai da teoria isolada (CS) e entra no mercado de trabalho (Engenharia). O código precisa ser testado e legível para terceiros.`,
      ementa: [
        // === EXISTENTES ===
        'Versionamento com Git: Branching, Merge Strategies e Rebase',
        'Clean Code e Refatoração de Projetos Legados',
        'Princípios SOLID e DRY na Prática',
        'Paradigmas: Orientação a Objetos vs Programação Funcional',
        'Design Patterns Essenciais (GoF) em Projetos Reais',
        'Desenvolvimento Guiado por Testes (TDD) e BDD',
        'Testes Automatizados: Unitários, Integração e E2E',
        'Integração e Entrega Contínua (CI/CD) com Pipelines',
        'Contêineres (Docker) e Padronização de Ambientes',
        'Desenvolvimento de APIs RESTful e GraphQL (Prática)',
        'Segurança Defensiva no Código (OWASP, JWT, CSRF)',
        'Processos Ágeis e Ciclo de Vida do Software (SDLC)',
        // === NOVOS ===
        'Monorepos vs Polyrepos: Estratégias de Repositório',
        'Code Review: Cultura, Checklist e Automação',
        'Pair Programming e Mob Programming na Prática',
        'Documentação Técnica: ADRs (Architecture Decision Records)',
        'Autenticação e Autorização (OAuth 2.0, OIDC, RBAC)',
        'WebSockets e Comunicação em Tempo Real',
        'Arquitetura Frontend Moderna (React, SPA, SSR, ISR)',
        'Arquitetura Backend: Camadas, Hexagonal e Clean Architecture',
        'ORMs e Query Builders: Prós e Contras',
        'Migrations de Banco de Dados em Produção sem Downtime',
        'Feature Flags: Deploy Desacoplado de Release',
        'Engenharia de Performance: Profiling e Bottleneck Analysis',
        'Observabilidade no Código: Logs Estruturados e Correlation IDs',
        'DevSecOps: Segurança Integrada no Pipeline de CI/CD',
        'Desenvolvimento com IA: Copilot, Cursor e AI-Augmented Coding',
        'Gestão de Dívida Técnica: Identificar, Medir e Pagar',
        'Trunk-Based Development vs GitFlow',
        'Contratos de API: OpenAPI/Swagger e Contract Testing',
        'Internacionalização (i18n) e Localização (l10n) de Software',
        'Acessibilidade no Código (a11y): ARIA e Semântica HTML'
      ]
    },
    {
      slug: 'arquitetura-software',
      nome: 'Arquitetura de Software',
      emoji: '🏛️',
      parent: 'tecnologia-hub',
      whyStart: 'Quando o sistema precisa atender a 1 milhão de usuários simultâneos, o código limpo não é suficiente. Você precisa desenhar como os sistemas conversam.',
      descricao: 'System Design, microsserviços, Cloud Computing e decisões de trade-offs.',
      contexto: `Foco: decisões macroestruturais de sistemas.
O aluno atua como Arquiteto ou Staff Engineer. O foco não é codar a regra de negócio, mas montar a infraestrutura que não cai.`,
      ementa: [
        // === EXISTENTES ===
        'Arquitetura de Monólitos vs Microsserviços: Quando migrar?',
        'System Design: Desenhando Sistemas em Grande Escala',
        'Bancos de Dados: Relacional vs NoSQL (Trade-offs reais)',
        'Caching, CDNs e Estratégias de Baixa Latência',
        'Mensageria e Event-Driven Architecture (Kafka, RabbitMQ)',
        'Arquiteturas Cloud Native e Serverless',
        'Orquestração de Contêineres em Produção (Kubernetes)',
        'Padrões de Resiliência: Circuit Breaker, Retries, Fallbacks',
        'Teorema CAP e Consistência de Dados Distribuídos',
        'Observabilidade: Logs, Métricas e Distributed Tracing',
        'Sistemas Distribuídos e Single Point of Failure (SPOF)',
        'Planejamento de Capacidade (Capacity Planning)',
        // === NOVOS ===
        'PACELC: Evolução do CAP para Trade-offs de Latência',
        'Modular Monolith: Alternativa Moderna aos Microsserviços',
        'CQRS (Command Query Responsibility Segregation)',
        'Event Sourcing: Histórico Imutável de Eventos',
        'Saga Pattern: Transações Distribuídas sem Two-Phase Commit',
        'Service Mesh (Istio, Linkerd) e Sidecar Pattern',
        'API Gateway: Rate Limiting, Throttling e Load Balancing',
        'Infrastructure as Code (Terraform, Pulumi, CDK)',
        'GitOps: Infraestrutura Declarativa com ArgoCD/Flux',
        'SRE (Site Reliability Engineering): SLOs, SLIs e Error Budgets',
        'Disaster Recovery: RPO, RTO e Estratégias de Failover',
        'Multi-Region e Multi-Cloud: Arquitetando para Disponibilidade Global',
        'FinOps: Otimização de Custos em Cloud (AWS/GCP/Azure)',
        'Zero Trust Architecture: Segurança sem Perímetro',
        'Edge Computing: Processamento Próximo ao Usuário',
        'Stateful Serverless: Durable Execution (Temporal, Step Functions)',
        'CRDTs: Dados Replicados sem Conflito (Local-First)',
        'Data Mesh: Dados como Produto por Domínio',
        'Arquitetura de Micro Frontends',
        'AIOps: Observabilidade e Self-Healing com IA',
        'Arquiteturas AI-Native: Desenhando Sistemas para LLMs e Agentes'
      ]
    }
  ]
};
